#!/bin/sh
#
# pygame        Starts pygame script.
#

start() {
    printf "Starting Pygame script: "
    /usr/bin/python3 /root/test1/main.py
	echo "OK"
}
stop() {
	printf "Stopping Pygame script: "
	killall python3
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
